# Generated by Django 2.1 on 2020-03-24 16:50

import accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_nafdacnumber_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_comany_image_path)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nafdac_number', models.OneToOneField(on_delete='', related_name='Nafdac_Number', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
