# Generated by Django 2.1 on 2020-03-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_drug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.DateField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='production_date',
            field=models.DateField(blank=True, max_length=250, null=True),
        ),
    ]
