# Generated by Django 2.1 on 2020-03-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200329_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='nafdac_number',
            field=models.ForeignKey(blank=True, null=True, on_delete='', to='accounts.Company'),
        ),
    ]
