# Generated by Django 2.1 on 2020-03-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200329_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='drug',
            name='production_date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
